In [1]:
import pandas as pd

# 2 main types

series = 1 dimentional

In [2]:
series = pd.series(["BMW","Mercedes","Audi"])

AttributeError: module 'pandas' has no attribute 'series'

"S" should be capital

In [3]:
series = pd.Series(["BMW","Mercedes","Audi"])

In [4]:
series

0         BMW
1    Mercedes
2        Audi
dtype: str

In [5]:
colors = pd.Series(["Red","Yellow","Green"])
colors

0       Red
1    Yellow
2     Green
dtype: str

dataframe = 2 dimentional

In [6]:
car_data = pd.DataFrame({"Car_Brand":series, "Color":colors})
car_data

  Car_Brand   Color
0       BMW     Red
1  Mercedes  Yellow
2      Audi   Green

In [7]:
#import data
car_sales = pd.read_csv("car-sales.csv")

In [8]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

axis = 0 means row  
axis = 1 means column

In [9]:
# exporting a dataframe
car_sales.to_csv("exported-car-sales.csv")

we can add a parameter (..... , index=False)  
this will not export the first index column

In [10]:
car_sales.to_csv("exported-car-sales-without-index.csv",index=False)

# Describe Data

In [11]:
# this is an attribute = some metadata about car-sales
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

car_sales.to_csv()  
this is a function = it does some action

In [12]:
car_columns = car_sales.columns
car_columns
# this is a list

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [13]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

some functions

In [14]:
car_sales.describe()
# works on only numeric columns

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [15]:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [16]:
car_sales.mean()

TypeError: Cannot perform reduction 'mean' with string dtype

In [18]:
car_sales.sum()

Make             ToyotaHondaToyotaBMWNissanToyotaHondaHondaToyo...
Colour               WhiteRedBlueBlackWhiteGreenBlueBlueWhiteWhite
Odometer (KM)                                               786014
Doors                                                           40
Price            $4,000.00$5,000.00$7,000.00$22,000.00$3,500.00...
dtype: object

In [ ]:
car_sales["Doors"].sum()
# for a single row

In [19]:
car_sales["Odometer (KM)"].mean()

np.float64(78601.4)

In [20]:
len(car_sales)
#number of rows

10

# Viewing and Selecting data

In [21]:
car_sales.head()
# top 5 rows of the data

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

so we manipulate the data and then call head function to view the changes

In [22]:
car_sales.tail(7)
# tail is also 5 by default, both head and tail can have arguments also

     Make Colour  Odometer (KM)  Doors       Price
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [27]:
# .loc i.e. location
animals = pd.Series(["panda","cat","dog","lion","tiger"],index=[10,5,9,3,3])
animals
# the series will be created with the index we gave it

10    panda
5       cat
9       dog
3      lion
3     tiger
dtype: str

In [28]:
animals.loc[10]

'panda'

In [29]:
animals.loc[3]

3     lion
3    tiger
dtype: str

In [30]:
# .iloc i.e. position
animals

10    panda
5       cat
9       dog
3      lion
3     tiger
dtype: str

In [31]:
animals.iloc[0]

'panda'

In [32]:
animals.iloc[2]

'dog'

In [33]:
# slicing is also available in iloc
animals.iloc[:3]

10    panda
5       cat
9       dog
dtype: str

In [36]:
# loc returns the location till that index
animals.loc[:5]

10    panda
5       cat
dtype: str